=== senbox-org/sen2like/sen2like/conf/Sen2Like_GIPP.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Level-2A_Ground_Image_Processing_Parameter"
                type="Level-2A_Ground_Image_Processing_ParameterType"/>
    <xs:complexType name="ProcessingType">
        <xs:sequence>
            <xs:element type="StringBoolType" name="doStitching"/>
            <xs:element type="StringBoolType" name="doGeometryKLT"/>
            <xs:element type="StringBoolType" name="doToa"/>
            <xs:element type="StringBoolType" name="doAtmcor"/>
            <xs:element type="StringBoolType" name="doNbar"/>
            <xs:element type="StringBoolType" name="doSbaf"/>
            <xs:element type="StringBoolType" name="doFusion"/>
            <xs:element type="StringBoolType" name="doPackager"/>
            <xs:element type="StringBoolType" name="doPackagerL2H"/>
            <xs:element type="StringBoolType" name="doPackagerL2F"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DirectoriesType">
        <xs:sequence>
            <xs:element type="xs:string" name="archive_dir"/>
            <xs:element type="xs:string" name="cams_dir"/>
            <xs:element type="xs:string" name="cams_hourly_dir"/>
            <xs:element type="xs:string" name="cams_climatology_dir"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DownloaderType">
        <xs:sequence>
            <xs:element type="xs:float" name="coverage"/>
            <xs:element type="xs:string" name="base_url"/>
            <xs:choice>
                <xs:sequence>
                    <xs:element type="xs:string" name="url_parameters_pattern_Sentinel2"/>
                    <xs:element type="xs:string" name="url_parameters_pattern_Landsat8"/>
                </xs:sequence>
                <xs:sequence>
                    <xs:element type="xs:integer" name="cloud_cover"/>
                    <xs:element type="xs:string" name="location_Landsat8"/>
                    <xs:element type="xs:string" name="location_Sentinel2"/>
                    <xs:element type="xs:string" name="url_parameters_pattern"/>
                    <xs:element type="xs:string" name="thumbnail_property"/>
                    <xs:element type="xs:string" name="cloud_cover_property"/>
                </xs:sequence>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GeometryType">
        <xs:sequence>
            <xs:element type="xs:string" name="reference_band"/>
            <xs:element type="StringBoolType" name="doMatchingCorrection"/>
            <xs:element type="xs:string" name="doAssessGeometry"/>
            <xs:element type="xs:string" name="references_map"/>
            <xs:element type="StringBoolType" name="force_geometric_correction" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AtmcorType">
        <xs:sequence>
            <xs:element type="StringBoolType" name="use_sen2cor"/>
            <xs:element type="xs:string" name="sen2cor_path"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="StitchingType">
        <xs:sequence>
            <xs:element type="xs:integer" name="reframe_margin"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="FusionType">
        <xs:sequence>
            <xs:element type="xs:string" name="predict_method"/>
            <xs:element type="xs:integer" name="predict_nb_products"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="OutputFormatType">
        <xs:sequence>
            <xs:element type="xs:integer" name="gain"/>
            <xs:element type="xs:integer" name="offset"/>
            <xs:element type="xs:string" name="output_format"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="COGoptionsType">
        <xs:sequence>
            <xs:element type="xs:string" name="interleave"/>
            <xs:element type="xs:integer" name="internal_tiling"/>
            <xs:element type="xs:integer" name="internal_overviews"/>
            <xs:element type="xs:string" name="downsampling_levels_10"/>
            <xs:element type="xs:string" name="downsampling_levels_15"/>
            <xs:element type="xs:string" name="downsampling_levels_20"/>
            <xs:element type="xs:string" name="downsampling_levels_30"/>
            <xs:element type="xs:string" name="downsampling_levels_60"/>
            <xs:element type="xs:string" name="resampling_algo_MASK"/>
            <xs:element type="xs:string" name="resampling_algo"/>
            <xs:element type="xs:string" name="compression"/>
            <xs:element type="xs:integer" name="predictor"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="JPEG2000optionsType">
        <xs:sequence>
            <xs:element type="StringBoolType" name="lossless_jpeg2000"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="MultiprocessingType">
        <xs:sequence>
            <xs:element type="xs:integer" name="number_of_process"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PackagerType">
        <xs:sequence>
            <xs:element type="xs:integer" name="quicklook_jpeg_quality"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="RunTimeType">
        <xs:sequence>
            <xs:element type="xs:integer" name="dx"/>
            <xs:element type="xs:integer" name="dy"/>
            <xs:element type="xs:string" name="freeze_dx_dy"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Level-2A_Ground_Image_Processing_ParameterType">
        <xs:sequence>
            <xs:element type="ProcessingType" name="Processing"/>
            <xs:element type="DirectoriesType" name="Directories"/>
            <xs:element type="DownloaderType" name="InputProductArchive"/>
            <xs:element type="GeometryType" name="Geometry"/>
            <xs:element type="AtmcorType" name="Atmcor"/>
            <xs:element type="FusionType" name="Fusion"/>
            <xs:element type="StitchingType" name="Stitching"/>
            <xs:element type="OutputFormatType" name="OutputFormat"/>
            <xs:element type="COGoptionsType" name="COGoptions"/>
            <xs:element type="JPEG2000optionsType" name="JPEG2000options"/>
            <xs:element type="MultiprocessingType" name="Multiprocessing"/>
            <xs:element type="PackagerType" name="Packager"/>
            <xs:element type="RunTimeType" name="RunTime"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="StringBoolType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="True"/>
            <xs:enumeration value="False"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== senbox-org/sen2like/sen2like/conf/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<Level-2A_Ground_Image_Processing_Parameter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                            xsi:noNamespaceSchemaLocation="Sen2Like_GIPP.xsd">
    <Processing>
        <doStitching>True</doStitching>
        <doGeometryKLT>True</doGeometryKLT>
        <doToa>True</doToa>
        <doInterCalibration>True</doInterCalibration>
        <doAtmcor>True</doAtmcor>
        <doNbar>True</doNbar>
        <doSbaf>True</doSbaf>
        <doFusion>True</doFusion>
        <doPackager>False</doPackager>
        <doPackagerL2H>False</doPackagerL2H>
        <doPackagerL2F>True</doPackagerL2F>
    </Processing>
    <Directories>
        <archive_dir>/data/HLS</archive_dir>
        <cams_dir>/data/CAMS/monthly</cams_dir>
        <cams_daily_dir>/data/CAMS/daily</cams_daily_dir>
        <cams_hourly_dir>/data/CAMS/hourly</cams_hourly_dir>
        <cams_climatology_dir>/data/CAMS/climatology/v1</cams_climatology_dir>
        <dem_dir>/data/AUX_DATA/DEM</dem_dir>
        <scl_dir>/data/AUX_DATA/SCL_maps_2.10</scl_dir>
    </Directories>
    <InputProductArchive>
        <coverage>0.5</coverage>
        <!-- Local -->
        <base_url>/data/PRODUCTS</base_url>
        <cloud_cover>11</cloud_cover>
        <url_parameters_pattern_Sentinel2>{base_url}/{mission}/{tile}</url_parameters_pattern_Sentinel2>
        <url_parameters_pattern_Landsat8>{base_url}/{mission}/{path}/{row}</url_parameters_pattern_Landsat8>
        <url_parameters_pattern_Landsat9>{base_url}/{mission}/{path}/{row}</url_parameters_pattern_Landsat9>

        <!--  Creodias -->
        <!--        <base_url>https://finder.creodias.eu/resto/api/collections</base_url>-->
        <!--        <cloud_cover>11</cloud_cover>-->
        <!--        <location_Landsat8>path={path}&amp;row={row}</location_Landsat8>-->
        <!--        <location_Landsat9>path={path}&amp;row={row}</location_Landsat9>-->
        <!--        <location_Sentinel2>processingLevel={s2_processing_level}&amp;productIdentifier=%25{tile}%25</location_Sentinel2>-->
        <!--        <url_parameters_pattern>{base_url}/{mission}/search.json?maxRecords=100&amp;_pretty=true&amp;cloudCover=%5B0%2C{cloud_cover}%5D&amp;startDate={start_date}&amp;completionDate={end_date}&amp;sortParam=startDate&amp;sortOrder=ascending&amp;status=all&amp;{location}&amp;dataset=ESA-DATASET</url_parameters_pattern>-->
        <!--        <thumbnail_property>properties/productIdentifier</thumbnail_property>-->
        <!--        <cloud_cover_property>properties/cloudCover</cloud_cover_property>-->
    </InputProductArchive>
    <Geometry>
        <reference_band>B04</reference_band>
        <doMatchingCorrection>True</doMatchingCorrection>
        <doAssessGeometry>B04</doAssessGeometry>
        <references_map>/data/References/references_map.json</references_map>
        <force_geometric_correction>False</force_geometric_correction>
    </Geometry>
    <Atmcor>
        <use_sen2cor>True</use_sen2cor>
        <sen2cor_path>../sen2cor/process.py</sen2cor_path>
    </Atmcor>
    <Nbar>
        <nbar_methode>VJB</nbar_methode>
        <vjb_coeff_matrice_dir>/data/Belen</vjb_coeff_matrice_dir>
    </Nbar>
    <Fusion>
        <predict_method>predict</predict_method>
        <predict_nb_products>2</predict_nb_products>
        <fusion_auto_check_band>B04</fusion_auto_check_band>
        <fusion_auto_check_threshold>0.1</fusion_auto_check_threshold>
    </Fusion>
    <Stitching>
        <reframe_margin>50</reframe_margin>
    </Stitching>
    <OutputFormat>
        <gain>10000</gain>
        <offset>0</offset>
        <output_format>COG</output_format>
    </OutputFormat>
    <COGoptions>
        <interleave>PIXEL</interleave>
        <internal_tiling>1024</internal_tiling>
        <internal_overviews>128</internal_overviews>
        <downsampling_levels_10>2</downsampling_levels_10>
        <downsampling_levels_15>2</downsampling_levels_15>
        <downsampling_levels_20>2 3 6</downsampling_levels_20>
        <downsampling_levels_30>2 4 6 12</downsampling_levels_30>
        <downsampling_levels_60>6 12 18 36</downsampling_levels_60>
        <resampling_algo_MASK>MODE</resampling_algo_MASK>
        <resampling_algo>AVERAGE</resampling_algo>
        <compression>LZW</compression>
        <predictor>1</predictor>
    </COGoptions>
    <JPEG2000options>
        <lossless_jpeg2000>True</lossless_jpeg2000>
    </JPEG2000options>
    <Multiprocessing>
        <number_of_process>5</number_of_process>
    </Multiprocessing>
    <Packager>
        <quicklook_jpeg_quality>75</quicklook_jpeg_quality>
    </Packager>
    <RunTime>
        <dx>0</dx>
        <dy>0</dy>
        <freeze_dx_dy>True</freeze_dx_dy>
    </RunTime>
</Level-2A_Ground_Image_Processing_Parameter>
